### ISSUE TITLE
error-messaging.md example doesn't work

### ISSUE THREAD

**Issue by j0057** [mirumee/ariadne-website#164]
The page https://ariadnegraphql.org/docs/error-messaging has this GraphQL schema example:

    type Mutation {
        login(username: String!, password: String!) {
            error: String
            user: User
        }
    }

Defining some kind of anonymous sub-object doesn't seem to be valid GraphQL schema, either with or without a `:` between the `)` and the `{`.

It should be something like this:

    type Mutation {
        login(username: String!, password: String!): LoginResult
    }

    type LoginResult {
        error: String
        user: User
    }

**Comment by rafalp** [comment]
Fixed. Thanks for reporting!
