### ISSUE TITLE
Confusing mutations docs typo

### ISSUE THREAD

**Issue by sometimescool22** [mirumee/ariadne-website#36]
In the last quoted text under [this](https://github.com/mirumee/ariadne-website/blob/master/docs/mutations.md#writing-resolvers) section, the docs state:

> __Recall that resolvers need to be bound to their respective resolvers__ via the make_executable_schema call. If you're following along from the introduction that call will look similar to the following:

Is it supposed to be `Recall that resolvers need to be bound to their respective schemas`?

**Comment by rafalp** [comment]
I've updated wording there. Thanks!
