### ISSUE TITLE
Modularization: "graphql" directory conflicts with graphql-core-next

### ISSUE THREAD

**Issue by patryk-tech** [mirumee/ariadne-website#41]
Hey! In [`docs/modularization.md`](https://github.com/mirumee/ariadne-website/blob/master/docs/modularization.md), you use the following layout:

```
graphql/
    types/
        __init__.py
        book.py
        query.py
        user.py
    __init__.py
    scalars.py
    schema.py
```

If I use that, I get the following exception:

```
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.8/site-packages/ariadne/__init__.py", line 1, in <module>
  from .enums import EnumType
File "/usr/local/lib/python3.8/site-packages/ariadne/enums.py", line 5, in <module>
  from graphql.type import GraphQLEnumType, GraphQLNamedType, GraphQLSchema
ModuleNotFoundError: No module named 'graphql.type'
```

Renaming `graphql` in my project root to e.g. `my_graphql` fixes it. Maybe it should be changed in the documentation, as `graphql-core-next` uses the name `graphql`.

**Comment by rafalp** [comment]
The part that docs are missing is higher level namespace that your `graphql` was supposed to live in, eg:

```
myproject/
  graphql/
      types/
          __init__.py
          book.py
          query.py
          user.py
      __init__.py
      scalars.py
      schema.py
  __init__.py
```

**Comment by patryk-tech** [comment]
@rafalp that makes sense.

I am using Django, which uses app namespaces, so I can't really do:
```python
import myproject  # raises ModuleNotFoundError
myproject.graphql ...
```

I think at least adding a note about the potential conflict might help others avoid similar issues, but it's not a huge thing :)

**Comment by rafalp** [comment]
I am aware of Django's guide telling people to put all their apps at project's root level, but it supports namespacing apps all-right, and it's good practice to use anyway as it helps against name conflicts. You can look at [Saleor](https://github.com/mirumee/saleor/tree/master/saleor) for example of Django project that uses root namespace, and [Misago](https://github.com/rafalp/Misago/tree/starlette/misago/graphql) for example implementation of modularization pattern described in the docs.

> I think at least adding a note about the potential conflict might help others avoid similar issues

Don't worry, I'll revisit this example so it will be less surprising for future users.

**Comment by patryk-tech** [comment]
Awesome, thanks.

> and it's good practice to use anyway as it helps against name conflicts.

Old habits die hard, but I'll try to start using that. Explicit code is always nice.

**Comment by rafalp** [comment]
I've finnaly found time to go about this. Thank you!
