### ISSUE TITLE
Update Docs About Returning None From Resolvers

### ISSUE THREAD

**Issue by joeyjoejoejr** [mirumee/ariadne-website#61]
I found this line in the docs really confusing and I'm pretty sure they are wrong based on my brief dive into the code.
https://github.com/mirumee/ariadne-website/blame/master/docs/error-messaging.md#L46

When you return none from a query resolover, you don't get any message like ""Requested item doesn't exist or you don't have permission to see it" instead you get the message "Cannot return null for non-nullable field" which can be found here: https://github.com/graphql-python/graphql-core/blob/2c2cae7cd90ffaa7286b3a48909d9b453eebec04/src/graphql/execution/execute.py#L703

For now I'm raising an error with the message I want, but this sent me down a rabbit hole trying to figure out why I wasn't getting a better message.  Am I wrong about this?  Am I missing something?  I would love for it to be this easy to handle missing/unauthorized access.

**Comment by rafalp** [comment]
This is in context of YOUR client displaying a message when `null` is returned from API:

> Your API result-handling logic may then interpret the response

**Comment by joeyjoejoejr** [comment]
Ok.  It makes sense now that you say it.  I think since it explicitly said that the query resolvers could return None.  I was thinking that this was some built in functionality.  Feel free to close this.  But it definitely thew me.

**Comment by rafalp** [comment]
I've reworded a message to be more to the point. Thanks for your feedback!
