### ISSUE TITLE
Add example for autoreload in the Django Integration docs

### ISSUE THREAD

**Issue by IgnisDa** [mirumee/ariadne-website#72]
By default, when you change the graphql files, `*.graphql`, the django server isn't reloaded. To register the change to a schema file, you will have to trigger a reload using another file (mostly this can be done by opening any watched file by django and then saving it). However this gets quickly exhausting when you are making a lot of active changes to your schema definition.

I have found a way to fix this very easily and want to add relevant documentation for the same.

Regards
Diptesh

**Comment by fhightower** [comment]
Hi Diptesh,

> I have found a way to fix this very easily and want to add relevant documentation for the same.

Thanks for posting this. Can you give more details about your solution or create a PR documenting the solution?

**Comment by rafalp** [comment]
Please note that we are deprecating `ariadne.contrib.django` for [ariadne_django](https://github.com/reset-button/ariadne_django).

**Comment by IgnisDa** [comment]
@rafalp I understand and support the depreciation. Where should I make a PR regarding the above?

**Comment by rafalp** [comment]
I would say that ariadne_django is the place, but they are looking maintainers so no promises it would be merged.
