### ISSUE TITLE
Outdated schema stitching section in apollo federation

### ISSUE THREAD

**Issue by alesso-x** [mirumee/ariadne-website#87]
The docs for [apollo-federation](https://ariadnegraphql.org/docs/apollo-federation) is outdated.

> You may have heard about schema stitching when searching for GraphQL solutions for merging multiple GraphQL servers into a single one. This approach was originally proposed back in 2018 and implemented by the Apollo Server, but it had considerable downsides which resulted in it being scrapped and federations being proposed as the new, better solution.

Schema stitching has not been scrapped and is supported by [the guild](https://the-guild.dev/blog/graphql-tools-v7). They released GraphqQL Tools v7 last year.

> GraphQL Tools v7, stitching is fairly comparable to Apollo Federation with automated query planning, merged types, and declarative schema directives. -> [graphql-tools](https://www.graphql-tools.com/docs/schema-stitching/)

**Comment by rafalp** [comment]
Note to self that we are actually planning to implement Python schema stitching utility for Ariadne.

**Comment by rafalp** [comment]
I've removed this part so we don't lie to folk thinking that federation is only way to combine schemas. Thanks for pointing this out!
